#!/bin/bash
#PBS -P ps29
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l mem=64GB
#PBS -l ncpus=16
#PBS -l storage=gdata/ps29+gdata/rt52+gdata/xp65+gdata/vk83
#PBS -j oe

module use /g/data/xp65/public/modules
module load conda/analysis3-26.03

cd /home/566/nd0349/access-om3-analysis/scripts

OUT_DIR="/g/data/ps29/nd0349/Fraser-2024/data/cleaned"

ESM_FILE="/scratch/ps29/nd0349/access-om3/archive/WW3-standalone-ERA5-dice-2013/experiment_datastore.json"
OUTPUT_FREQUENCY="fx"

for year in {2013..2015}; do
    echo "Processing ${year}"

    python3 map_altika_tracks_onto_ww3.py \
        --year "${year}" \
        --esm-file "${ESM_FILE}" \
        --output-frequency "${OUTPUT_FREQUENCY}" \
        --out-dir "${OUT_DIR}" \
        --version "0.15" \
        --n-points 300 \
        --max-lat -40 \
        --extend-factor 10.0
done